[package]
name = "counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.40.2"
csv = "1.1.6"
regex = "1"
clap = { version = "4.1.4", features = ["derive"] }
